
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build:       # This job runs in the build stage, which runs first.
  script:
    - apt update
    - npm install -g @angular/cli
    - npm install
    - ng build --prod
    - dotnet restore
    - dotnet build --no-restore --configuration Release
    - echo "BUILD SUCCESSFUL"
  artifacts:
    paths:
      - dist

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - dotnet test --no-build --configuration Release --filter Category!=Integration

publish:
  stage: publish
  only:
    - main
  script:
    - dotnet publish -c Release -o ./publish
  artifacts:
    paths:
      - ./publish/
