# Render handles the SSL certificate automatically at the edge
services:
  - type: web
    name: catalog
    plan: free
    env: docker
    dockerContext: .
    dockerfilePath: ./catalog.api/render.Dockerfile
    ports:
      - port: 80
        http: true
    envVars:
      - key: render
        value: true
      - key: ASPNETCORE_URLS
        value: http://+
      - key: DB_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    plan: free
    postgresMajorVersion: 16